# .travis.yml
language: ruby
rvm:
  - 2.2.2
env:
  - DB=postgresql
script:
  - RAILS_ENV=test bundle exec rake db:migrate --trace
  - bundle exec rake db:test:prepare
  - bundle exec rake
  - bundle exec rspec
before_script:
  - psql -c 'create database users_test' -U postgres